  name: mobile_prosset
  description: "ProSSet – Profit Analyzer and Ground Asset Control System"
  publish_to: 'none'

  version: 1.0.0+1

  environment:
    sdk: ^3.9.0

  dependencies:
    flutter:
      sdk: flutter

    # Firebase (updated for FlutterFire compatibility with Dart 3.9)
    firebase_core: ^3.0.0
    firebase_auth: ^5.0.0
    shared_preferences: ^2.3.2
    cloud_firestore: ^5.0.0
    firebase_storage: ^12.0.0
    image_picker: ^1.2.0



    # State management
    provider: ^6.1.2

    # Utilities
    intl: ^0.19.0
    cupertino_icons: ^1.0.6

    # Charts & PDF
    fl_chart: ^0.66.2
    pdf: ^3.11.0
    printing: ^5.14.2

  dev_dependencies:
    flutter_test:
      sdk: flutter
    flutter_lints: ^3.0.1
    flutter_launcher_icons: ^0.14.4

  flutter_launcher_icons:
    android: true
    ios: true
    image_path: "assets/logo.png"


  flutter:
    uses-material-design: true